language: R
sudo: false
cache: packages
warnings_are_errors: true
os:
- linux
- osx
osx_image: xcode9
r_packages:
- Rcpp
- RcppArmadillo
- ggplot2
- glmnet
- ncvreg
- covr
before_install:
- Rscript -e "source('build_steps.R'); before_install()"
after_success:
- Rscript -e "source('build_steps.R'); after_success(); unlink('build_steps.R')"
branches:
  except:
  - build
r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-manual"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
  local_dir: "."
  target_branch: build
  condition: $TRAVIS_OS_NAME = "linux"
env:
  global:
  - secure: iLOGXi0VNACYbgktYsfsuwZ/3Xba4mBv28pt/RiAYH+keJULplPaFq1Vw5oIm6aLaD5ESfCPdgS/BArNqySvqjbh//bVwqiz66QTgZjAXpwXBtWiVEUn6g8En9uEa1DHlh3qA+yrqum0mqSHWeK89wAHJ9+VPF1rjr/KyL4HArHYsDw4QqzHn/Vqr8MezLnunmjJ4zam72eqXiBSbFJA1qtb+GpBYpANOiWXBU/aBrlZlQn3Ze49mx0avHRqebMU4WUCmlD4w4sHF9aRFVUWCbHthSQpPHRjwWNm9OMmSwcLqQzt8hppsR+CkYaJtlR6RGokY5x+TX89RrahQ2NyqPw5hNu2E/wh5cvN+C5DceCUdH+0k9yFFhgRr+DR9Y1MdHnfV0jwenFPirOUvgPzwXRPoE0yXl/VLFpvLUz6BIJMBgdLntT1uN3mY9rtUuMZ726N5InRJn18/K1wSvzEPFWeiQdok6Nfs6OJzRT28VSSPWbTGRYe43NgzE0GA65NJQx4mpXZ8bS2rcDdmx7xFRxLOWJXa0qnGGAL0goOonQHZTTvS1810mjLvq3R3dmsfS84otgeDO4oXsXqd29Ey3aouonKx/xqda+HAkkjtvSvO1kLJrru6HI9AECG3+j62WxZuIJJQGNL0fdrnxrgkyhtt2u9KTG3PERbHVtENN8=
