# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

moma_set_logger_level_cpp <- function(level) {
    invisible(.Call('_MoMA_moma_set_logger_level_cpp', PACKAGE = 'MoMA', level))
}

moma_get_logger_level_cpp <- function() {
    .Call('_MoMA_moma_get_logger_level_cpp', PACKAGE = 'MoMA')
}

moma_log_cpp <- function(level, x) {
    invisible(.Call('_MoMA_moma_log_cpp', PACKAGE = 'MoMA', level, x))
}

prox_lasso <- function(x, l) {
    .Call('_MoMA_prox_lasso', PACKAGE = 'MoMA', x, l)
}

prox_nnlasso <- function(x, l) {
    .Call('_MoMA_prox_nnlasso', PACKAGE = 'MoMA', x, l)
}

prox_scad <- function(x, l, g = 3.7) {
    .Call('_MoMA_prox_scad', PACKAGE = 'MoMA', x, l, g)
}

prox_mcp <- function(x, l, g = 4) {
    .Call('_MoMA_prox_mcp', PACKAGE = 'MoMA', x, l, g)
}

mat_norm <- function(u, S_u) {
    .Call('_MoMA_mat_norm', PACKAGE = 'MoMA', u, S_u)
}

sfpca <- function(X, Omega_u, Omega_v, alpha_u = 0L, alpha_v = 0, P_u = "LASSO", P_v = "LASSO", lambda_u = 0, lambda_v = 0, gamma = 3.7, EPS = 1e-6, MAX_ITER = 1e+3L, solver = "ISTA") {
    .Call('_MoMA_sfpca', PACKAGE = 'MoMA', X, Omega_u, Omega_v, alpha_u, alpha_v, P_u, P_v, lambda_u, lambda_v, gamma, EPS, MAX_ITER, solver)
}

test_norm <- function(x) {
    .Call('_MoMA_test_norm', PACKAGE = 'MoMA', x)
}

